const OK = 200;
const CREATED = 201;
const UPDATE = 202;
const NOTFOUND = 404;
const BADREQUEST = 400;
const INTERNAL_SERVER_ERROR = 500;

module.exports = {
  OK,
  CREATED,
  UPDATE,
  NOTFOUND,
  BADREQUEST,
  INTERNAL_SERVER_ERROR,
};
